/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Mediatypes {
  MediaType?: MediaType;
}

export enum MediaType {
  Image = 0,
  YouTube = 1,
  GitHub = 2,
  YouTubeShort = 3
}
