/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Skilllevels {
  SkillLevelEnum: SkillLevelEnum;
}

export enum SkillLevelEnum {
  Proficient = 0,
  Used = 1,
  Dabbled = 2
}
